config/routes.rb
Rails.application.routes.draw do

  root 'watching#feed'

  scope 'api' do
    get 'subscriptions' => 'api#subscriptions', as: :api_subscriptions
    get 'users' => 'api#users', as: :api_users
    get 'pages' => 'api#pages', as: :api_pages
    get 'stats' => 'api#stats', as: :api_stats

    scope 'embed' do
      post 'page' => 'api#embed_find_page', as: :embed_find_page
      post 'page/update-selector' => 'api#embed_update_page_selector', as: :embed_update_page_selector
    end

    get '/page-preview' => 'api#page_preview', as: :api_page_preview
  end

  scope '/watching' do
    get '/' => 'watching#index', as: :watching

    resources :pages do
      get '/latest-change' => 'pages#latest_change', on: :member
      get '/snapshots' => 'pages#snapshots', on: :member
      get '/setup-compare' => 'pages#setup_compare', on: :member, as: :setup_compare
      get '/compare/:before_id/:after_id' => 'pages#compare', on: :member
    end
  end

  get '/changes/page/:change_id' => 'changes#page', as: :page_change
  post '/changes/resend/:change_id' => 'changes#resend', as: :resend_change_notifications
  patch '/changes/:change_id' => 'changes#update', as: :change

  scope '/embed' do
    get 'inject' => 'embed#inject'
    get 'iframe' => 'embed#iframe'
  end

  scope '/integrations' do
    get '/' => 'integrations#index', as: :integrations
    resources :slack, as: 'slack_integrations', controller: 'slack_integrations'
    resources :sqs, as: 'sqs_integrations', controller: 'sqs_integrations'
  end

  get '/help' => 'static#help', as: :help

  resources :users do
    get  '/invite' => 'users#invite', as: :invite
    post '/invite' => 'users#create_invite', as: :create_invite
  end

  scope '/login' do
    get '/' => 'sessions#new', as: :login
    get '/token' => 'sessions#token', as: :token_session
    post '/' => 'sessions#create', as: :create_session
    get 'unknown' => 'sessions#unknown_user', as: :unknown_user
    get 'expired/:user_id' => 'sessions#expired_token', as: :expired_token
  end
  post '/logout' => 'sessions#destroy', as: :logout

end

app/models/sqs_integration.rb
class SqsIntegration < ActiveRecord::Base

  validates :queue_url, length: { minimum: 10 }
  validate :starts_with_https
  def starts_with_https
    if queue_url.to_s.split('').first(5).join('') != 'https'
      errors.add(:queue_url, "must begin with https")
    end
  end

  include Rails.application.routes.url_helpers

  def send_notification(change)
    puts "sqs_integration#send_notification #{self.queue_url}"

    page_name = change&.after&.page&.name
    text = "#{page_name} changed #{change&.after&.page&.url}"

    payload = {
      "page_name": page_name,
      "text": text,
      "change_page_url": page_change_url(change),

      "url": change&.after&.page&.url,
      "event": "update",
      "source": "klaxon",
      "type": "external",
      "eventTS": Time.now.to_i
    }

    SqsNotification.perform(self.queue_url, payload)
    return payload
  end

end

app/controllers/sqs_integrations_controller.rb
class SqsIntegrationsController < ApplicationController
  before_action :set_sqs_integration, only: [:show, :edit, :update, :destroy]

  # GET /sqs_integrations
  def index
    @sqs_integrations = SqsIntegration.all
  end

  # GET /sqs_integrations/1
  def show
  end

  # GET /sqs_integrations/new
  def new
    @sqs_integration = SqsIntegration.new
  end

  # GET /sqs_integrations/1/edit
  def edit
  end

  # POST /sqs_integrations
  def create
    @sqs_integration = SqsIntegration.new(sqs_integration_params)

    if @sqs_integration.save
      redirect_to integrations_path, notice: 'SQS integration was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sqs_integrations/1
  def update
    if @sqs_integration.update(sqs_integration_params)
      redirect_to integrations_path, notice: 'SQS integration was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sqs_integrations/1
  def destroy
    @sqs_integration.destroy
    redirect_to integrations_path, notice: 'SQS integration was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sqs_integration
      @sqs_integration = SqsIntegration.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sqs_integration_params
      params.require(:sqs_integration).permit(:queue_url)
    end
end

app/views/sqs_integrations/_form.html.erb
<%= simple_form_for(@sqs_integration) do |f| %>
  <%= f.error_notification %>

<div class="klax-section klax-spacer-lg">
  <div class="container">
    <div class="row klax-spacer-md">
      <div class="col-md-12">
        <h4>Details</h4>
      </div>
    </div>
    <div class="row">
      <form class="form-horizontal">
        <div class="form-group form-group-lg">
          <label class="col-sm-1">Queue URL</label>
          <div class="col-sm-11">
            <%= f.input :queue_url, label: false, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group form-group-lg">
          <div class="col-md-9">
            <!-- negative space -->
          </div>
          <div class="col-md-3">
            <%= f.button :submit, "Create SQS Integration", class: "btn btn-default btn-lg btn-block" %>
          </div>
        </div>
      </form>
    </div>
  </div><!-- /.container -->
</div>

<% end %>

app/views/sqs_integrations/edit.html.erb
<div class="klax-section klax-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Editing SQS Integration</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <p class="lead">Integrations allow you to push alerts to various platforms. For now, Klaxon supports Slack and Amazon SQS. We hope to add more in the future. If you’re interested in helping, <a href="https://github.com/themarshallproject/klaxon">visit our repo.</a></p>
      </div>
      <div class="col-md-3">
        <!-- negative space -->
      </div>
      <div class="col-md-3">
        <%= link_to 'Delete? It’s Permanent.', @sqs_integration, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-lg btn-block" %>
      </div>
    </div>
  </div><!-- /.container -->
</div>

<%= render 'form' %>

app/views/sqs_integrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing SQS Integrations</h1>

<table>
  <thead>
    <tr>
      <th>Queue url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sqs_integrations.each do |sqs_integration| %>
      <tr>
        <td><%= sqs_integration.queue_url %></td>
        <td><%= link_to 'Show', sqs_integration %></td>
        <td><%= link_to 'Edit', edit_sqs_integration_path(sqs_integration) %></td>
        <td><%= link_to 'Destroy', sqs_integration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New SQS integration', new_sqs_integration_path %>

app/views/sqs_integrations/new.html.erb
<div class="klax-section klax-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>New SQS Integration</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <p class="lead">Integrations allow you to push alerts to various platforms. For now, Klaxon supports Slack and Amazon SQS. We hope to add more in the future. If you’re interested in helping, <a href="https://github.com/themarshallproject/klaxon">visit our repo.</a></p>
      </div>
      <div class="col-md-6">
        <!-- negative space -->
      </div>
    </div>
  </div><!-- /.container -->
</div>
<%= render 'form' %>

app/views/sqs_integrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>SQS Queue url:</strong>
  <%= @sqs_integration.queue_url %>
</p>

<%= link_to 'Edit', edit_sqs_integration_path(@sqs_integration) %> |
<%= link_to 'Back', sqs_integrations_path %>