config/routes.rb
Rails.application.routes.draw do

  root 'watching#feed'

  scope 'api' do
    get 'subscriptions' => 'api#subscriptions', as: :api_subscriptions
    get 'users' => 'api#users', as: :api_users
    get 'pages' => 'api#pages', as: :api_pages
    get 'stats' => 'api#stats', as: :api_stats

    scope 'embed' do
      post 'page' => 'api#embed_find_page', as: :embed_find_page
      post 'page/update-selector' => 'api#embed_update_page_selector', as: :embed_update_page_selector
    end

    get '/page-preview' => 'api#page_preview', as: :api_page_preview
  end

  scope '/watching' do
    get '/' => 'watching#index', as: :watching

    resources :pages do
      get '/latest-change' => 'pages#latest_change', on: :member
      get '/snapshots' => 'pages#snapshots', on: :member
      get '/setup-compare' => 'pages#setup_compare', on: :member, as: :setup_compare
      get '/compare/:before_id/:after_id' => 'pages#compare', on: :member
    end
  end

  get '/changes/page/:change_id' => 'changes#page', as: :page_change
  post '/changes/resend/:change_id' => 'changes#resend', as: :resend_change_notifications
  patch '/changes/:change_id' => 'changes#update', as: :change

  scope '/embed' do
    get 'inject' => 'embed#inject'
    get 'iframe' => 'embed#iframe'
  end

  scope '/integrations' do
    get '/' => 'integrations#index', as: :integrations
    resources :slack, as: 'slack_integrations', controller: 'slack_integrations'
    resources :sqs, as: 'sqs_integrations', controller: 'sqs_integrations'
  end

  get '/help' => 'static#help', as: :help

  resources :users do
    get  '/invite' => 'users#invite', as: :invite
    post '/invite' => 'users#create_invite', as: :create_invite
  end

  scope '/login' do
    get '/' => 'sessions#new', as: :login
    get '/token' => 'sessions#token', as: :token_session
    post '/' => 'sessions#create', as: :create_session
    get 'unknown' => 'sessions#unknown_user', as: :unknown_user
    get 'expired/:user_id' => 'sessions#expired_token', as: :expired_token
  end
  post '/logout' => 'sessions#destroy', as: :logout

end

app/views/pages/_form.html.erb
<%= simple_form_for(@page) do |f| %>
<%= f.error_notification %>

<div class="klax-section klax-spacer-lg">
  <div class="container">
    <div class="row klax-spacer-md">
      <div class="col-md-12">
        <h4>Details</h4>
      </div>
    </div>
    <div class="row">
        <div class="form-group form-group-lg">
          <label class="col-sm-1">Title</label>
          <div class="col-sm-11">
            <%= f.input :name, label: false, class: 'form-control', as: :string %>
          </div>
        </div>
        <div class="form-group form-group-lg">
          <label class="col-sm-1">Site</label>
          <div class="col-sm-11">
            <%= f.input :url, label: false, class: 'form-control', as: :string %>
          </div>
        </div>
        <div class="form-group form-group-lg">
          <label class="col-sm-1">Selector</label>
          <div class="col-sm-11">
            <%= f.input :css_selector, label: false, class: 'form-control', as: :string %>
          </div>
        </div>
    </div>
  </div><!-- /.container -->
</div>

<div class="klax-section klax-spacer-lg">
  <div class="container">
    <div class="row klax-spacer-md">
      <div class="col-md-12">
        <h4>Notifications</h4>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 klax-spacer-md">
        <h5>Email Subscriptions</h5>
        <p>Which users added to Klaxon should get an email when this item changes?</p>

        <% @users.each do |user| %>
          <div class="checkbox">
            <label>
              <%= check_box_tag "page[subscriptions][]", "user:#{user.id}", user.is_subscribed_to?(@page) %>
              <%= user.display_name %>
            </label>
          </div>
        <% end %>

      </div>

      <% if @slack_integrations.empty? %>

        <div class="col-md-3 klax-spacer-md">
          <h5>Slack</h5>
          <p>It looks like you haven't configured any Slack notifications yet, would you like to? <%= link_to "Go to settings.", integrations_path %>
      <% else %>
        <div class="col-md-3 klax-spacer-md">
          <h5>Slack</h5>
          <p>Which of the Slack channels that you’ve added should get notification when this item changes?</p>

          <% @slack_integrations.each do |slack| %>
            <div class="checkbox">
              <label>
                <%= check_box_tag "page[subscriptions][]", "slack:#{slack.id}", slack.is_subscribed_to?(@page) %>
                <%= slack.channel %>
              </label>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="col-md-3 klax-spacer-md disabled">
<!--         <h5>Twitter</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tincidunt semper orci, eget molestie orci ullamcorper eu. Curabitur viverra ligula a dolor scelerisque, at tincidunt.</p> -->
      </div>
      <div class="col-md-3 klax-spacer-md disabled">
<!--         <h5>RSS</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tincidunt semper orci, eget molestie orci ullamcorper eu. Curabitur viverra ligula a dolor scelerisque, at tincidunt.</p> -->
      </div>
    </div>
  </div><!-- /.container -->
</div>

<div class="klax-section klax-spacer-lg">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= f.button :submit, label: 'Save', class: "btn btn-default btn-lg btn-block" %>
      </div>
    </div>
  </div><!-- /.container -->
</div>
<% end %>

<div class="klax-section klax-spacer-lg">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-md-offset-9">
        <%= link_to 'Delete Page Forever', @page, method: :delete, data: { confirm: 'Are you sure? This will delete all snapshots and changes associated with this page. There is no undo.' }, class: "btn btn-default btn-block btn-danger" %>
      </div>
    </div>
  </div><!-- /.container -->
</div>

app/views/pages/edit.html.erb
<div class="klax-section klax-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Edit an Item</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <p class="lead">Watching an item means that each time it changes, Klaxon will save a version of it, known as a “snapshot.”</p>
      </div>
      <div class="col-md-6">
        <!-- negative space -->
      </div>
    </div>
  </div><!-- /.container -->
</div>

<%= render 'form' %>

<% if @page.page_snapshots.count > 2 %>

  <div class="klax-section klax-spacer-lg">
    <div class="container">
      <div class="row klax-spacer-md">
        <div class="col-md-12">
          <h4>Activity</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3 klax-spacer-md">
          <h2><%= @page.page_snapshots.count %></h2>
          <p class="lead">total times the item has changed since you started watching it, which was <%= @page.created_at.strftime("%A, %B %d, %Y at %H:%M") %>.</p>
        </div>
        <div class="col-md-3 klax-spacer-md">
          <h2>TK%</h2>
          <p class="lead">is the average amount of the item that changes.</p>
        </div>
        <div class="col-md-3 klax-spacer-md">
          <h2><%= distance_of_time_in_words(@page.calculate_median(@page.snapshot_time_deltas)) %></h2>
          <p class="lead">amount of time, roughly, between each change. We anticipate the next change will occur on <%= @page.predicted_snapshot.strftime("%A, %B %d, %Y at %H:%M") %>.</p>
        </div>
        <div class="col-md-3 klax-spacer-md">
          <h2><%= time_ago_in_words @page.page_snapshots.last.created_at %></h2>
          <p class="lead">since the last change was captured at <%= @page.page_snapshots.last.created_at.strftime("%A, %B %d, %Y at %H:%M") %></p>
        </div>
      </div>
    </div><!-- /.container -->
  </div>

<% end %>

app/views/pages/index.html.erb
<%= render partial:'layouts/bookmarklet' %>

<div class="klax-section klax-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Watching</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <p class="lead">Watching an item means that each time it changes, Klaxon will save a version of it, known as a “snapshot.” Below you’ll see all the items and can click to see the latest snapshot.</p>
      </div>
      <div class="col-md-3">
        <!-- negative space -->
      </div>
      <div class="col-md-3">
        <%= link_to 'Manually Watch an Item', new_page_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  </div><!-- /.container -->
</div>

<div class="klax-section klax-spacer-lg">
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th>Created</th>
          <th>Name</th>
          <th>Site</th>
          <th>Selector</th>
          <th>Creator</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @pages.each do |page| %>
        <tr>
          <td><%= page.created_at.strftime("%m/%d/%Y at %I:%M%p") %></td>
          <td><%= page.name %></td>
          <td><%= page.domain.truncate(40) %></td>
          <td><code><%= page.css_selector %></code></td>
          <td><%= page&.user&.display_name %></td>
          <td><% if page.page_snapshots.count > 1 %><%= link_to "Latest Change", latest_change_page_path(page), class: "btn btn-default btn-block" %><% end %></td>
          <td><%= link_to 'Edit', edit_page_path(page), class: "btn btn-default btn-block" %></td>
          <td><td><%= link_to 'Delete', page, method: :delete, data: { confirm: 'Are you sure? This will delete all snapshots and changes associated with this page. There is no undo.' }, class: "btn btn-default btn-block" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/pages/new.html.erb
<div class="klax-section klax-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Watch a New Item</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <p class="lead">Watching an item means that each time it changes, Klaxon will save a version of it, known as a “snapshot.”</p>
      </div>
      <div class="col-md-6">
        <!-- negative space -->
      </div>
    </div>
  </div><!-- /.container -->
</div>

<%= render 'form' %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @page.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @page.url %>
</p>

<p>
  <strong>Css selector:</strong>
  <%= @page.css_selector %>
</p>

<p>
  <strong>User:</strong>
  <%= @page.user_id %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/snapshots.html.erb
<%= form_tag setup_compare_page_path, method: :get do %>
  <div class="klax-section klax-topper">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>All Snapshots</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <p class="lead">
            Below are all of the snapshots, or versions, of <b><%= @page.name %></b> going back to <%= @page.created_at.strftime("%A, %B %d, %Y at %H:%M") %>. Start by selecting an older version, then select a newer version to compare it against.</p>
        </div>
        <div class="col-md-3">
          <!-- negative space -->
        </div>
        <div class="col-md-3">
          <%= submit_tag "Compare", class: "btn btn-default btn-lg btn-block" %>
        </div>
      </div>
    </div><!-- /.container -->
  </div>

  <div class="klax-section klax-spacer-lg">
    <div class="container">

      <div class="row">
        <div class="col-md-6">
          <h4 class="klax-spacer-md">Select the Older Version</h4>

          <% @snapshots.each_with_index do |snapshot, index| %>
            <div class="row klax-spacer-sm"><!-- row -->
              <div class="col-md-3">
                <div class="radio" style="margin: 0;">
                  <label>
                    <input class="klax-js-snapshot-before" type="radio" name="before" data-index="<%= index %>" value="<%= snapshot.id %>">
                    <code><%= snapshot.sha2_hash.first(8) %></code>
                  </label>
                </div>
              </div>
              <div class="col-md-3">
                <p><%= snapshot.created_at %></p>
              </div>
              <div class="col-md-5">
                <p><b></b></p>
              </div>
            </div><!-- end row -->
          <% end %>
        </div>


        <div class="col-md-6">
          <h4 class="klax-spacer-md">Select the Newer Version</h4>

          <% @snapshots.each_with_index do |snapshot, index| %>
            <div class="row klax-spacer-sm"><!-- row -->
              <div class="col-md-3">
                <div class="radio" style="margin: 0;">
                  <label>
                    <input class="klax-js-snapshot-after" type="radio" name="after" data-index="<%= index %>" value="<%= snapshot.id %>" style="display: none;">
                    <code><%= snapshot.sha2_hash.first(8) %></code>
                  </label>
                </div>
              </div>
              <div class="col-md-3">
                <p><%= snapshot.created_at %></p>
              </div>
              <div class="col-md-5">
                <p><b></b></p>
              </div>
            </div><!-- end row -->
          <% end %>

        </div>
      </div>
    </div><!-- /.container -->
  </div>
<% end %><!-- form_tag -->

<script>

  $(document).ready(function() {
    $(".klax-js-snapshot-before[data-index='0']").attr("disabled","");
    $(".klax-js-snapshot-before[data-index='1']").click();
    $(".klax-js-snapshot-after[data-index='0']").show().click();
    $(".klax-js-snapshot-before").click(function(){
      var index = $(this).data("index");
      $(".klax-js-snapshot-after").each(function(){
        var thisIndex = $(this).data("index");
        if (index <= thisIndex) {
          $(this).attr("disabled","");
          $(this).css("display","none");
        } else {
          $(this).css("display","block");
          $(this).removeAttr("disabled","");
          if (thisIndex == (index - 1)) {
            $(this).click();
          }
        }
      });
    });
  });

</script>