config/routes.rb
Rails.application.routes.draw do

  root 'watching#feed'

  scope 'api' do
    get 'subscriptions' => 'api#subscriptions', as: :api_subscriptions
    get 'users' => 'api#users', as: :api_users
    get 'pages' => 'api#pages', as: :api_pages
    get 'stats' => 'api#stats', as: :api_stats

    scope 'embed' do
      post 'page' => 'api#embed_find_page', as: :embed_find_page
      post 'page/update-selector' => 'api#embed_update_page_selector', as: :embed_update_page_selector
    end

    get '/page-preview' => 'api#page_preview', as: :api_page_preview
  end

  scope '/watching' do
    get '/' => 'watching#index', as: :watching

    resources :pages do
      get '/latest-change' => 'pages#latest_change', on: :member
      get '/snapshots' => 'pages#snapshots', on: :member
      get '/setup-compare' => 'pages#setup_compare', on: :member, as: :setup_compare
      get '/compare/:before_id/:after_id' => 'pages#compare', on: :member
    end
  end

  get '/changes/page/:change_id' => 'changes#page', as: :page_change
  post '/changes/resend/:change_id' => 'changes#resend', as: :resend_change_notifications
  patch '/changes/:change_id' => 'changes#update', as: :change

  scope '/embed' do
    get 'inject' => 'embed#inject'
    get 'iframe' => 'embed#iframe'
  end

  scope '/integrations' do
    get '/' => 'integrations#index', as: :integrations
    resources :slack, as: 'slack_integrations', controller: 'slack_integrations'
    resources :sqs, as: 'sqs_integrations', controller: 'sqs_integrations'
  end

  get '/help' => 'static#help', as: :help

  resources :users do
    get  '/invite' => 'users#invite', as: :invite
    post '/invite' => 'users#create_invite', as: :create_invite
  end

  scope '/login' do
    get '/' => 'sessions#new', as: :login
    get '/token' => 'sessions#token', as: :token_session
    post '/' => 'sessions#create', as: :create_session
    get 'unknown' => 'sessions#unknown_user', as: :unknown_user
    get 'expired/:user_id' => 'sessions#expired_token', as: :expired_token
  end
  post '/logout' => 'sessions#destroy', as: :logout

end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController
  def index
    @slack_integrations = SlackIntegration.all
    @sqs_integrations = SqsIntegration.all    
  end
end

app/helpers/integrations_helper.rb
module IntegrationsHelper
end

app/views/integrations/index.html.erb
<div class="klax-section klax-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Integrations</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <p class="lead">Integrations allow you to push alerts to various platforms. For now, Klaxon supports Slack. We hope to add more in the future. If you’re interested in helping, <a href="https://github.com/themarshallproject/klaxon">visit our repo.</a></p>
      </div>
       <div class="col-md-3">
      </div>
      <div class="col-md-3">
      </div>
    </div>
  </div><!-- /.container -->
</div>


<div class="klax-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
          <h4 style="margin-top: 0;" class="klax-spacer-md">Slack</h4>
      </div>
      <div class="col-md-3">
        <%= link_to "Create Slack Integration", new_slack_integration_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
    <% if @slack_integrations.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Channel</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @slack_integrations.each do |integration| %>
        <tr>
          <td><%= integration.channel %></td>
          <td><%= link_to "Edit", edit_slack_integration_path(integration), class: 'btn btn-default btn-block pull-right', style: "max-width: 136px !important;" %>
        </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
    <div class="row">
      <div class="col-md-9">
          <h4 style="margin-top: 0;" class="klax-spacer-md">SQS</h4>
      </div>
      <div class="col-md-3">
        <%= link_to "Create SQS Integration", new_sqs_integration_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
    <% if @sqs_integrations.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Queue URL</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @sqs_integrations.each do |integration| %>
        <tr>
          <td><%= integration.queue_url %></td>
          <td><%= link_to "Edit", edit_sqs_integration_path(integration), class: 'btn btn-default btn-block pull-right', style: "max-width: 136px !important;" %>
        </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>