config/routes.rb
Rails.application.routes.draw do

  root 'watching#feed'

  scope 'api' do
    get 'subscriptions' => 'api#subscriptions', as: :api_subscriptions
    get 'users' => 'api#users', as: :api_users
    get 'pages' => 'api#pages', as: :api_pages
    get 'stats' => 'api#stats', as: :api_stats

    scope 'embed' do
      post 'page' => 'api#embed_find_page', as: :embed_find_page
      post 'page/update-selector' => 'api#embed_update_page_selector', as: :embed_update_page_selector
    end

    get '/page-preview' => 'api#page_preview', as: :api_page_preview
  end

  scope '/watching' do
    get '/' => 'watching#index', as: :watching

    resources :pages do
      get '/latest-change' => 'pages#latest_change', on: :member
      get '/snapshots' => 'pages#snapshots', on: :member
      get '/setup-compare' => 'pages#setup_compare', on: :member, as: :setup_compare
      get '/compare/:before_id/:after_id' => 'pages#compare', on: :member
    end
  end

  get '/changes/page/:change_id' => 'changes#page', as: :page_change
  post '/changes/resend/:change_id' => 'changes#resend', as: :resend_change_notifications
  patch '/changes/:change_id' => 'changes#update', as: :change

  scope '/embed' do
    get 'inject' => 'embed#inject'
    get 'iframe' => 'embed#iframe'
  end

  scope '/integrations' do
    get '/' => 'integrations#index', as: :integrations
    resources :slack, as: 'slack_integrations', controller: 'slack_integrations'
    resources :sqs, as: 'sqs_integrations', controller: 'sqs_integrations'
  end

  get '/help' => 'static#help', as: :help

  resources :users do
    get  '/invite' => 'users#invite', as: :invite
    post '/invite' => 'users#create_invite', as: :create_invite
  end

  scope '/login' do
    get '/' => 'sessions#new', as: :login
    get '/token' => 'sessions#token', as: :token_session
    post '/' => 'sessions#create', as: :create_session
    get 'unknown' => 'sessions#unknown_user', as: :unknown_user
    get 'expired/:user_id' => 'sessions#expired_token', as: :expired_token
  end
  post '/logout' => 'sessions#destroy', as: :logout

end

app/views/layouts/_bookmarklet.html.erb
<% bookmarklet_js = "javascript:(function(){document.body.appendChild(document.createElement('script')).src='#{inject_url()}';})();" %>

<div class="klax-topper">
  <div class="container">
    <div class="jumbotron">
      <% if @current_user.pages.empty? %>
        <h1 class="klax-no-border" style="padding-top: 0;">Watch Your First Item</h1>
      <% else %>
        <h3 class="klax-no-border" style="padding-top: 0;">Bookmarklet</h3>
      <% end %>
      <p>To watch a web page, drag the “Add to Klaxon” button below to your bookmark bar. When on the page you want to watch, click the bookmark. <!-- To watch a file such as an image or document, <a href="#">enter it manually</a> instead.--></p>
      <a class="btn btn-lg" href="<%= bookmarklet_js %>" role="button">Add to Klaxon</a>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <svg style="padding-top: 2px;" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="23px" height="20px" viewBox="0 0 100 86.9" enable-background="new 0 0 100 86.9" xml:space="preserve"><g><path id="logo-no-fill" fill="none" d="M38.5,33.7c-2.6-12.6-1.8-19.5-1.8-19.5S23.8,54.4,54.3,76.7c-3.1-6-5.6-11.7-7.7-16.9c5.4-2.3,8-9.3,5.7-16.2C50.1,36.9,44.1,32.7,38.5,33.7z"/><polygon fill="none" points="79.3,39.2 79.3,39.2 79.3,39.2 "/><path fill="#FF0B3A" d="M33.2,5.9c-20,34.4-10.7,30.4-21.6,34.2C8.4,41.2,4,43.6,2,46.3C-3,53,1.2,71,15.1,71.7c21,1,4.2-2,35.9,13C94.6,105.4,53.7-29.4,33.2,5.9z M46.5,59.8c2.1,5.3,4.6,10.9,7.7,16.9C23.8,54.4,36.7,14.2,36.7,14.2s-0.8,6.9,1.8,19.5c5.6-1,11.6,3.2,13.8,9.9C54.5,50.5,51.9,57.5,46.5,59.8z"/><path fill="#FF0B3A" d="M78.7,11.2l-1.9-1.1c-1.1-0.7-2.7-0.3-3.4,0.9l-4.6,7.7c-0.7,1.2-0.3,2.7,0.9,3.4l1.9,1.1c0.4,0.2,0.8,0.4,1.3,0.4c0.9,0,1.7-0.5,2.1-1.2l4.6-7.7C80.2,13.4,79.8,11.9,78.7,11.2z"/><path fill="#FF0B3A" d="M99.8,33.6l-0.5-2.1c-0.2-0.8-1-1.7-2.6-1.7c-0.4,0-0.9,0.1-1.3,0.2L78.9,34c-0.7,0.2-1.9,0.6-2.5,1.6L76,36.5l0.7,2.9c0.1,0.4,0.6,1.7,2.6,1.7c0.4,0,0.9-0.1,1.3-0.2L97,36.8C99.5,36.2,100.1,34.7,99.8,33.6z M79.3,39.2L79.3,39.2L79.3,39.2L79.3,39.2z"/><path fill="#FF0B3A" d="M90.5,58.4l-7.7-4.7c-1.1-0.7-2.7-0.3-3.4,0.8l-1.1,1.9c-0.7,1.2-0.3,2.7,0.9,3.4l7.7,4.7c0.4,0.2,0.8,0.4,1.3,0.4c0.9,0,1.7-0.5,2.1-1.2l1.1-1.9c0.3-0.6,0.4-1.2,0.3-1.9C91.4,59.3,91,58.8,90.5,58.4z"/></g></svg>
        <b>Klaxon</b></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse pull-right">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Feed", root_path %></li>
        <li><a href="<%= pages_path %>">Watching</a></li>
        <li><a href="<%= help_path %>">Help</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Integrations", integrations_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", logout_path, method: :post %></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Klaxon</title>

  <% if current_user.present? %>
    <script>
      window.klaxonUser = <%= current_user.to_json.html_safe %>;
    </script>
  <% end %>

  <script>
    window.klaxonReturnUrl = "<%= params[:return_to] %>";
  </script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield(:body_classes) %>">

<%= render partial: 'layouts/nav' %>

<%= yield %>

</body>
</html>

app/views/layouts/user_mailer.html.erb
<!DOCTYPE html>
<html>
<head>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
<style>
body {
  color: #ff0b3a;
  padding: 30px;
  font-family: "Helvetica Neue", Helvetica, sans-serif;
}
p {
  font-size: 14px;
  line-height: 1.4em;
  word-wrap: break-word;
}

h1, h2, h3, h4, h5, h6 {
  border-top: 0.2em solid #ff0b3a;
  padding-top: 10px;
}

h1 {
  margin-top: 0;
  margin-bottom: 0;
  font-size: 5.063em;
}

h2 {font-size: 3.375em;}

h3 {font-size: 2.25em;}

h4 {font-size: 1.5em;}

.container {
  max-width: 1200px;
  margin: 0 auto;
}

.klax-app-name {
  padding-bottom: 50px;
  font-weight: bold;
  font-size: 18px;
}

.klax-button {
  padding: 10px 16px;
  font-size: 18px;
  line-height: 1.33333;
  border: 1px solid #ff0b3a;
  display: block;
  text-align: center;
}

.klax-button:hover, .klax-button:hover a {
  background-color: #ff0b3a;
  color: #ffffff !important;
  text-decoration: none;
}

.klax-button {
  text-decoration: none !important;
}

.klax-lead {
  margin-bottom: 20px;
  font-size: 16px;
  font-weight: 300;
  line-height: 1.4;
  font-size: 21px;
}

.klax-fine-print {
  margin-top: 30px;
  font-size: 12px;
}

a {
  color: #ff0b3a;
}

</style>
</head>
<body>

<%= yield %>

</body>
</html>